FROM bloben/nginx:0.0.1

COPY --from=bloben/admin:development ./usr/app/admin ./usr/app/admin/
COPY --from=bloben/calendar:development ./usr/app/calendar ./usr/app/calendar/
COPY --from=bloben/api:development ./usr/app/api/ ./usr/app/api/

COPY nginx/init.sh /bin/
RUN chmod u+x /bin/init.sh

COPY /nginx/nginx.conf /etc/nginx

CMD /bin/init.sh
