FROM bloben/nginx:development

ARG DOCKER_IMAGE_VERSION
ENV DOCKER_IMAGE_VERSION=development
# api port
ENV PORT=8081
ENV NODE_ENV=production
ENV HOST=localhost

COPY --from=bloben/admin:development ./usr/app/admin ./usr/app/admin/
COPY --from=bloben/calendar:development ./usr/app/calendar ./usr/app/calendar/
COPY --from=bloben/api:development ./usr/app/api/ ./usr/app/api/
COPY --from=bloben/tasks:development ./usr/app/tasks/ ./usr/app/tasks/

COPY nginx/init.sh /bin/
RUN chmod u+x /bin/init.sh

COPY nginx/nginx.conf /etc/nginx

CMD /bin/init.sh
